apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopping-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shopping-cart-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_REDIS_PORT
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SERVER_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_EXPIRATION
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: CORS_ALLOWED_ORIGINS
        - name: CORS_ALLOWED_METHODS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: CORS_ALLOWED_METHODS
        - name: CORS_ALLOWED_HEADERS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: CORS_ALLOWED_HEADERS
        - name: CORS_ALLOW_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: CORS_ALLOW_CREDENTIALS
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
